USE [SQLMonitor]
GO
/*
DROP TABLE [Archive].[DatabaseBackupHistory]
DROP TABLE [Archive].[DatabaseConfigurations]
DROP TABLE [Archive].[DatabaseTables]
DROP TABLE [Archive].[DatabaseUsers]
DROP TABLE [Archive].[IndexUsageStats]
DROP TABLE [Archive].[MissingIndexStats]
DROP TABLE [Archive].[ServerAgentConfig]
DROP TABLE [Archive].[ServerAgentJobs]
DROP TABLE [Archive].[ServerAgentJobsHistory]
DROP TABLE [Archive].[ServerConfigurations]
DROP TABLE [Archive].[ServerDatabases]
DROP TABLE [Archive].[ServerEndpoints]
DROP TABLE [Archive].[ServerErrorLog]
DROP TABLE [Archive].[ServerFreeSpace]
DROP TABLE [Archive].[ServerInfo]
DROP TABLE [Archive].[ServerLogins]
DROP TABLE [Archive].[ServerServers]
DROP TABLE [Archive].[ServerTriggers]
GO
*/

CREATE SYNONYM [Archive].[DatabaseBackupHistory] FOR [SQLMonitorArchive].[Archive].[DatabaseBackupHistory]
CREATE SYNONYM [Archive].[DatabaseConfigurations] FOR [SQLMonitorArchive].[Archive].[DatabaseConfigurations]
CREATE SYNONYM [Archive].[DatabaseTables] FOR [SQLMonitorArchive].[Archive].[DatabaseTables]
CREATE SYNONYM [Archive].[DatabaseUsers] FOR [SQLMonitorArchive].[Archive].[DatabaseUsers]
CREATE SYNONYM [Archive].[IndexUsageStats] FOR [SQLMonitorArchive].[Archive].[IndexUsageStats]
CREATE SYNONYM [Archive].[MissingIndexStats] FOR [SQLMonitorArchive].[Archive].[MissingIndexStats]
CREATE SYNONYM [Archive].[ServerAgentConfig] FOR [SQLMonitorArchive].[Archive].[ServerAgentConfig]
CREATE SYNONYM [Archive].[ServerAgentJobs] FOR [SQLMonitorArchive].[Archive].[ServerAgentJobs]
CREATE SYNONYM [Archive].[ServerAgentJobsHistory] FOR [SQLMonitorArchive].[Archive].[ServerAgentJobsHistory]
CREATE SYNONYM [Archive].[ServerConfigurations] FOR [SQLMonitorArchive].[Archive].[ServerConfigurations]
CREATE SYNONYM [Archive].[ServerDatabases] FOR [SQLMonitorArchive].[Archive].[ServerDatabases]
CREATE SYNONYM [Archive].[ServerEndpoints] FOR [SQLMonitorArchive].[Archive].[ServerEndpoints]
CREATE SYNONYM [Archive].[ServerErrorLog] FOR [SQLMonitorArchive].[Archive].[ServerErrorLog]
CREATE SYNONYM [Archive].[ServerFreeSpace] FOR [SQLMonitorArchive].[Archive].[ServerFreeSpace]
CREATE SYNONYM [Archive].[ServerInfo] FOR [SQLMonitorArchive].[Archive].[ServerInfo]
CREATE SYNONYM [Archive].[ServerLogins] FOR [SQLMonitorArchive].[Archive].[ServerLogins]
CREATE SYNONYM [Archive].[ServerServers] FOR [SQLMonitorArchive].[Archive].[ServerServers]
CREATE SYNONYM [Archive].[ServerTriggers] FOR [SQLMonitorArchive].[Archive].[ServerTriggers]
GO
