USE [SQLMonitor]
GO

DROP SYNONYM IF EXISTS [Archive].[DatabaseBackupHistory]
DROP SYNONYM IF EXISTS [Archive].[DatabaseConfigurations]
DROP SYNONYM IF EXISTS [Archive].[DatabaseTables]
DROP SYNONYM IF EXISTS [Archive].[DatabaseUsers]
DROP SYNONYM IF EXISTS [Archive].[IndexUsageStats]
DROP SYNONYM IF EXISTS [Archive].[MissingIndexStats]
DROP SYNONYM IF EXISTS [Archive].[ServerAgentConfig]
DROP SYNONYM IF EXISTS [Archive].[ServerAgentJobs]
DROP SYNONYM IF EXISTS [Archive].[ServerAgentJobsHistory]
DROP SYNONYM IF EXISTS [Archive].[ServerConfigurations]
DROP SYNONYM IF EXISTS [Archive].[ServerDatabases]
DROP SYNONYM IF EXISTS [Archive].[ServerEndpoints]
DROP SYNONYM IF EXISTS [Archive].[ServerErrorLog]
DROP SYNONYM IF EXISTS [Archive].[ServerFreeSpace]
DROP SYNONYM IF EXISTS [Archive].[ServerInfo]
DROP SYNONYM IF EXISTS [Archive].[ServerLogins]
DROP SYNONYM IF EXISTS [Archive].[ServerMSB]
DROP SYNONYM IF EXISTS [Archive].[ServerServers]
DROP SYNONYM IF EXISTS [Archive].[ServerTriggers]
GO

CREATE SYNONYM [Archive].[DatabaseBackupHistory] FOR [SQLMonitorArchive].[Archive].[DatabaseBackupHistory]
CREATE SYNONYM [Archive].[DatabaseConfigurations] FOR [SQLMonitorArchive].[Archive].[DatabaseConfigurations]
CREATE SYNONYM [Archive].[DatabaseTables] FOR [SQLMonitorArchive].[Archive].[DatabaseTables]
CREATE SYNONYM [Archive].[DatabaseUsers] FOR [SQLMonitorArchive].[Archive].[DatabaseUsers]
CREATE SYNONYM [Archive].[IndexUsageStats] FOR [SQLMonitorArchive].[Archive].[IndexUsageStats]
CREATE SYNONYM [Archive].[MissingIndexStats] FOR [SQLMonitorArchive].[Archive].[MissingIndexStats]
CREATE SYNONYM [Archive].[ServerAgentConfig] FOR [SQLMonitorArchive].[Archive].[ServerAgentConfig]
CREATE SYNONYM [Archive].[ServerAgentJobs] FOR [SQLMonitorArchive].[Archive].[ServerAgentJobs]
CREATE SYNONYM [Archive].[ServerAgentJobsHistory] FOR [SQLMonitorArchive].[Archive].[ServerAgentJobsHistory]
CREATE SYNONYM [Archive].[ServerConfigurations] FOR [SQLMonitorArchive].[Archive].[ServerConfigurations]
CREATE SYNONYM [Archive].[ServerDatabases] FOR [SQLMonitorArchive].[Archive].[ServerDatabases]
CREATE SYNONYM [Archive].[ServerEndpoints] FOR [SQLMonitorArchive].[Archive].[ServerEndpoints]
CREATE SYNONYM [Archive].[ServerErrorLog] FOR [SQLMonitorArchive].[Archive].[ServerErrorLog]
CREATE SYNONYM [Archive].[ServerFreeSpace] FOR [SQLMonitorArchive].[Archive].[ServerFreeSpace]
CREATE SYNONYM [Archive].[ServerInfo] FOR [SQLMonitorArchive].[Archive].[ServerInfo]
CREATE SYNONYM [Archive].[ServerLogins] FOR [SQLMonitorArchive].[Archive].[ServerLogins]
CREATE SYNONYM [Archive].[ServerMSB] FOR [SQLMonitorArchive].[Archive].[ServerMSB]
CREATE SYNONYM [Archive].[ServerServers] FOR [SQLMonitorArchive].[Archive].[ServerServers]
CREATE SYNONYM [Archive].[ServerTriggers] FOR [SQLMonitorArchive].[Archive].[ServerTriggers]
GO
